In [2]:
import numpy as np
import pandas as pd
import plotly.plotly as py
import plotly.graph_objs as go
import matplotlib.pyplot as plt

In [3]:
columns = ['population','profit']
df_1 = pd.read_csv('./data/ex1data1.txt',names=columns)
#df_1['bias'] = 1
#df_1.head()
df_1.insert(1,'bias',1)
df_1.head()

population  bias   profit
0      6.1101     1  17.5920
1      5.5277     1   9.1302
2      8.5186     1  13.6620
3      7.0032     1  11.8540
4      5.8598     1   6.8233

In [4]:
trace1 = go.Scatter(
    x = df_1['population'],
    y = df_1['profit'],
    mode = "markers",
    marker = dict(color='cray')
)

layout = go.Layout(
    xaxis = dict(title='population',
                ticklen = 5,
                gridwidth = 2 
                ),
    yaxis = dict(title = 'profit',
                ticklen = 5,
                gridwidth = 2)
)
data = [trace1]
fig = dict(data=data,layout=layout)
py.iplot(fig,filename='scatter_point')


KeyboardInterrupt: 

In [ ]:
df_1[df_1['profit'] < 0].sum()

In [64]:
#m = df_1['population'].as_matrix().size
#X = df_1['population'].as_matrix()
#y = df_1['profit'].as_matrix()
#def cost(theta,X,y):
#    return ((1. /(2 * m)) * np.dot((y - np.dot(theta,X)).T, y - np.dot(theta,X)))
    

In [66]:
#cost(np.array([0] * m),X,y)


In [5]:
X = df_1[[0,1]]
#X.head()
print X.size
y = df_1[[2]]
print y.size
m = X.shape[0]
print m
print y.shape
#y.head()

194
97
97
(97, 1)


In [6]:
def cost(theta,X,y,size):
    #print np.dot(theta.T,X)
    #print np.dot(theta.T,X).transpose()
    #theta.shape = (2,1)
    #print X.shape
    #print (y - np.dot(theta,X)).T.shape
    #print np.array([[ 32.07273388]]).shape
    #print np.dot( y - np.dot(theta,X), (y - np.dot(theta,X)).T).shape
    #print np.dot(X,theta)
    #print y - np.dot(X,theta).reshape(m,
    return float((1.0 / (2 * m )) *  np.dot((y - np.dot(X,theta).reshape(size,1)).T, y - np.dot(X,theta).reshape(size,1)))

In [7]:
cost(np.array([0,0]).reshape(2,1),X,y,m)

32.072733877455676

In [8]:
iterations = 15000
alpha = 0.01 #learning rate
def gradientdecent(X,y,size,inittheta=np.array([0,0]).reshape(2,1)):
    res = inittheta
    #print np.dot(X,res).shape
    #print y.shape
    #print np.dot(X,res) - y
    #print np.dot(X.T,(np.dot(X,res) - y))
    thetahist = []
    for _ in xrange(iterations):
        thetahist.append(res)
        res = res - (alpha * 1.0 / size) * np.dot(X.T,(np.dot(X,res) - y))
    print res
    return res,thetahist
    

In [9]:
t,thetahist = gradientdecent(X,y,m)
t.shape

[[ 1.19303364]
 [-3.89578088]]


(2, 1)

In [10]:
trace1 = go.Scatter(
    x = df_1['population'],
    y = df_1['profit'],
    mode = "markers",
    marker = dict(color='red')
)
trace2 = go.Scatter(
    x = df_1['population'],
    y = np.dot(df_1[[0,1]] ,t),
    mode = "lines",
    marker = dict(color='green')
)
data = [trace1,trace2]
py.iplot(data,name='reg.pdf')

KeyboardInterrupt: 

In [ ]:
trace3 = go.Scatter(
    x = range(150),
    y = map(lambda x:cost(x,X,y,m),thetahist),
    mode = "lines+markers",
    line = dict(color="blue",shape="spline")
)

layout3 = go.Layout(
    xaxis = dict(title="iter times"),
    yaxis = dict(title="cost")
)
fig = go.Figure(data=[trace3],layout=layout3)
py.iplot(fig,name="cost.pdf")

multiple linear regression

In [12]:
column = ['square','bedroom','price']
df_2 = pd.read_csv('./data/ex1data2.txt',names=column)
df_2.head()

square  bedroom   price
0    2104        3  399900
1    1600        3  329900
2    2400        3  369000
3    1416        2  232000
4    3000        4  539900

In [25]:
X_2 = df_2[[0,1]]
y_2 = df_2[[2]]
print X_2.shape
print y_2.shape
print X_2['square'].head()
m_2 = X_2.shape[0]
print m_2


(47, 2)
(47, 1)
0    2104
1    1600
2    2400
3    1416
4    3000
Name: square, dtype: int64
47


In [ ]:
trace4 = go.Scatter3d(
    x = X_2['square'],
    y = X_2['bedroom'],
    z = y_2['price'],
    mode = "markers"
    
)
py.iplot([trace4],name='3d plot1.pdf')

In [ ]:
#cost(np.array([0,0,0]).reshape(3,1),X_2,y_2,m_2)

In [26]:
#gradientdecent(X_2,y_2,m_2,np.array([0.,0.,0.]).reshape(3,1))
# normalize the data:
# when the data is too big ,it will cause nan and cannot work anymore
norm_X_2 = X_2.copy()
#norm_y_2 = y_2.copy()
#print norm_X_2.mean(axis=0)
#print norm_X_2.std(axis=0)
norm_X_2 = (norm_X_2 - norm_X_2.mean(axis=0)) / norm_X_2.std(axis=0)
#norm_y_2 = (norm_y_2 - norm_y_2.mean()) / norm_y_2.std()
norm_X_2.insert(2,"bias",1.)
print norm_X_2


      square   bedroom  bias
0   0.130010 -0.223675   1.0
1  -0.504190 -0.223675   1.0
2   0.502476 -0.223675   1.0
3  -0.735723 -1.537767   1.0
4   1.257476  1.090417   1.0
5  -0.019732  1.090417   1.0
6  -0.587240 -0.223675   1.0
7  -0.721881 -0.223675   1.0
8  -0.781023 -0.223675   1.0
9  -0.637573 -0.223675   1.0
10 -0.076357  1.090417   1.0
11 -0.000857 -0.223675   1.0
12 -0.139273 -0.223675   1.0
13  3.117292  2.404508   1.0
14 -0.921956 -0.223675   1.0
15  0.376643  1.090417   1.0
16 -0.856523 -1.537767   1.0
17 -0.962223 -0.223675   1.0
18  0.765468  1.090417   1.0
19  1.296484  1.090417   1.0
20 -0.294048 -0.223675   1.0
21 -0.141790 -1.537767   1.0
22 -0.499157 -0.223675   1.0
23 -0.048673  1.090417   1.0
24  2.377392 -0.223675   1.0
25 -1.133356 -0.223675   1.0
26 -0.682873 -0.223675   1.0
27  0.661026 -0.223675   1.0
28  0.250810 -0.223675   1.0
29  0.800701 -0.223675   1.0
30 -0.203448 -1.537767   1.0
31 -1.259189 -2.851859   1.0
32  0.049477  1.090417   1.0
33  1.429868 -

In [27]:
print cost(np.array([0,0,0]).reshape(3,1),norm_X_2,y_2,m_2)
print m_2
print norm_X_2.as_matrix()
print y_2
print type(y_2)

31781471762.9
47
[[  1.30009869e-01  -2.23675187e-01   1.00000000e+00]
 [ -5.04189838e-01  -2.23675187e-01   1.00000000e+00]
 [  5.02476364e-01  -2.23675187e-01   1.00000000e+00]
 [ -7.35723065e-01  -1.53776691e+00   1.00000000e+00]
 [  1.25747602e+00   1.09041654e+00   1.00000000e+00]
 [ -1.97317285e-02   1.09041654e+00   1.00000000e+00]
 [ -5.87239800e-01  -2.23675187e-01   1.00000000e+00]
 [ -7.21881404e-01  -2.23675187e-01   1.00000000e+00]
 [ -7.81023044e-01  -2.23675187e-01   1.00000000e+00]
 [ -6.37573110e-01  -2.23675187e-01   1.00000000e+00]
 [ -7.63567023e-02   1.09041654e+00   1.00000000e+00]
 [ -8.56737193e-04  -2.23675187e-01   1.00000000e+00]
 [ -1.39273340e-01  -2.23675187e-01   1.00000000e+00]
 [  3.11729182e+00   2.40450826e+00   1.00000000e+00]
 [ -9.21956312e-01  -2.23675187e-01   1.00000000e+00]
 [  3.76643089e-01   1.09041654e+00   1.00000000e+00]
 [ -8.56523009e-01  -1.53776691e+00   1.00000000e+00]
 [ -9.62222960e-01  -2.23675187e-01   1.00000000e+00]
 [  7.65467

In [28]:
theta_2,theta_hist_2 = gradientdecent(norm_X_2.as_matrix(),y_2,m_2,inittheta=np.array([0.,0.,0.]).reshape(3,1))

[[ 110631.05027884]
 [  -6649.47427082]
 [ 340412.65957447]]


In [ ]:
trace5 = go.Scatter(
    x = range(1500),
    y = map(lambda x:cost(x,norm_X_2,norm_y_2,m_2),theta_hist_2),
    mode = "lines+markers",
    line = dict(color="yellow",shape="spline")
)

layout5 = go.Layout(
    xaxis = dict(title="iter times"),
    yaxis = dict(title="cost")
)
fig = go.Figure(data=[trace5],layout=layout5)
py.iplot(fig,name="cost.pdf")

In [36]:
print "Check of result: What is price of house with 1650 square feet and 3 bedrooms?"
ytest = np.array([1650.,3.])
y_norm_test = (ytest - X_2.mean(axis=0)) / X_2.std(axis=0)
#print X_2.mean(axis=0).shape
#print X_2.std(axis=0).shape
np.insert(y_norm_test,2,1.)
#y_norm_test = np.insert(y_norm_test.as_matrix(),2,1.)

Check of result: What is price of house with 1650 square feet and 3 bedrooms?


In [34]:
print theta_2.shape
print np.dot(theta_2.T,y_norm_test)

(3, 1)
[  1.82861697e+08]
